#!/bin/bash
#PBS -N 3DZD_gen 
#PBS -q default
#PBS -l nodes=1:ppn=8
#PBS -l walltime=10:00:00
cd $PBS_O_WORKDIR
source /optnfs/common/miniconda3/etc/profile.d/conda.sh
conda activate py3

timestamp() {
  date +"%T"
}

echo "$(timestamp): starting 3D binding site Zernike descriptors extraction"

python /dartfs-hpc/rc/home/y/f002tsy/cbklab/Mattox/lec_gly_binding/scripts/pocketAnalysis/getZernike.py 

echo "$(timestamp): Processing done, exiting..."

exit 0
